config/routes.rb
Rails.application.routes.draw do
  root 'sessions#homepage'
  resources :users,
    path_names: { new: 'signup'}
  get 'study_exercises' => 'study_exercises#study_exercises'
  get 'ruby_on_rails_exercises' => 'study_exercises#ruby_on_rails_exercises'
  get 'updated_content' => 'study_exercises#updated_content'
  get 'lrthw' => 'study_exercises#lrthw'
  get 'number_letters_and_variables' => 'study_exercises#number_letters_and_variables'
  get 'methods_and_flow_control' => 'study_exercises#methods_and_flow_control'
  get 'git_101' => 'study_exercises#git_101'
  get 'git_102' => 'study_exercises#git_102'

  get 'useful_sources' => 'useful_sources#useful_sources'
  get 'reading_blogs' => 'useful_sources#reading_blogs'
  get 'build_my_brand' => 'useful_sources#build_my_brand'
  get 'pivotal_tracker' => 'useful_sources#pivotal_tracker'

  get 'adventure' => 'coding_adventure#adventure'
  get 'adventure_paths' => 'coding_adventure#adventure_paths'
  get 'adventure_start' => 'coding_adventure#adventure_start'
  get 'adventure_number_1' => 'coding_adventure#adventure_number_1'
  get 'adventure_number_2' => 'coding_adventure#adventure_number_2'
  get 'adventure_number_3' => 'coding_adventure#adventure_number_3'
  get 'adventure_number_4' => 'coding_adventure#adventure_number_4'
  get 'adventure_number_5' => 'coding_adventure#adventure_number_5'
  get 'adventure_number_6' => 'coding_adventure#adventure_number_6'
  get 'adventure_letter_1' => 'coding_adventure#adventure_letter_1'
  get 'adventure_letter_2' => 'coding_adventure#adventure_letter_2'
  get 'adventure_letter_3' => 'coding_adventure#adventure_letter_3'
  get 'adventure_letter_4' => 'coding_adventure#adventure_letter_4'

  get 'login' => 'sessions#login'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

end

app/models/painting.rb
# before_create :default_name
#
# def default_name
#   self.name ||= File.basename(image.filename, '.*').titleize if image
# end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password(validations:false)
  validates :email, uniqueness:true, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/ }
  validates :first_name, presence:true

  has_many :user_paths, dependent: :destroy
  has_many :user_questions, through: :user_paths
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/coding_adventure_controller.rb
class CodingAdventureController < ApplicationController
  def adventure
  end

  def adventure_paths
  end

  def adventure_start
  end

  def adventure_number_1
  end

  def adventure_number_2
  end

  def adventure_number_3
  end

  def adventure_number_4
  end

  def adventure_number_5
  end

  def adventure_number_6
  end

  def adventure_letter_1
  end

  def adventure_letter_2
  end

  def adventure_letter_3
  end

  def adventure_letter_4
  end
end

app/controllers/painting_controller.rb
# class PaintingController < ApplicationController
#   def create
#     @painting = Painting.create(params[:painting])
#   end
# end

app/controllers/paths_controller.rb
class PathsController < ApplicationController
  before_action :set_path, only: [:start]
  def adventure_1

  end

  def start
    begin
      @user_path = @path.user_path(current_user)
      @redirect = @user_path.next_user_question ? @user_path.next_user_question : @user_path
      redirect_to @redirect
    rescue => ex
      flash[:error] = ex.message
      redirect_to root_path
    end
  end

  private
  def set_path
    @path = Path.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def homepage
  end

  def login
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path,
        notice: "Welcome back #{user.first_name.titleize}"
    else
      flash[:error] = 'Invalid email or password'
      render :login
    end
  end

  def destroy
    if user = current_user
      session.delete(:user_id)
      redirect_to root_path,
        notice: "You logged out successfully"
    end
  end
end

app/controllers/study_exercises_controller.rb
class StudyExercisesController < ApplicationController
  def study_exercises
  end

  def ruby_on_rails_exercises
  end

  def updated_content
  end

  def lrthw
  end

  def number_letters_and_variables
  end

  def methods_and_flow_control
  end

  def git_101
  end

  def git_102
  end
end

app/controllers/useful_sources_controller.rb
class UsefulSourcesController < ApplicationController
  def useful_sources
  end

  def useful_sources
  end

  def build_my_brand
  end

  def pivotal_tracker
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path,
        notice: "Thank you for signing up #{@user.first_name.titlecase}"
    else
      render :new
    end
  end

  def index
    @users = User.all
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:first_name, :middle_name, :last_name, :email, :password, :password_confirmation, :wordpress, :github, :course, :user_type, :bio)
  end
end

app/controllers/users_list_controller.rb
class UsersListController < ApplicationController
  def users_list
    @users = User.all
  end

  def user_params
    params.require(:user).permit(:first_name, :middle_name, :last_name, :email, :password, :password_confirmation, :wordpress, :github, :course, :bio)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/coding_adventure/adventure.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta content="text/html; charset=windows-1252" http-equiv="content-type">
  <title>Study Tool Coding Adventure Page</title>

  <style type="text/css">
      table {width: 900px; height: 368px; border: 2px solid blue; cellpadding: 2px; cellspacing: 2px;}

      ul, li {decoration:none; list-style-type:none; padding: 0px; margin: 0px;}
      #smallmenu {display:block; font-weight:bold; float:left; color:blue; padding:2px; width:1000px;text-align:center; background-color: blue; text-decoration:none;}
      ul#smallmenu li {float:left;}

  </style>

  <link rel="stylesheet" type="text/css" href="skiingstyles.css">

</head>
<body>

<h1>Welcome, Developer Students</h1>
<table>
  <tbody>
  <tr>
    <% if current_user %>
        <li role="presentation" class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
            <%= image_tag 'adventure_begin.jpg' %>
            <button type="button" class="btn btn-default btn-lg"><%= link_to 'Start my Adventure', adventure_start_path %></button>
          </a>
        </li>
    <% else %>
    <td>
      <p id="openpara"><h3>
        Welcome to Ruby on Rails Adventure.
        You and YOU ALONE are in charge of your coding adventure.
        Please remember this is an adventure, anything can happen due to your coding skill.
        Let's see how far you can go in your adventure. Good luck, and have fun!
        <%= link_to 'Signup', new_user_path %> to start,
        or <%= link_to 'Login', login_path %> if you are current user.
      </h3></p>
    </td>
    <% end %>
  </tr>
  </tbody>
</table>

app/views/coding_adventure/adventure_letter_1.html.erb
<p><h2>How can we tell if those are letters in Ruby?</h2></p>

<div class="list-group">
  A. <a href="adventure_letter_2" class="list-group-item">Letters and strings in Ruby are surrounded with quote.</a>
  B. <a href="https://v.cdn.vine.co/r/avatars/E51A1CF382994084191392436224_17e0f8d8036.3.1_RHXbRCzGF7gXOMMjM.DDjqYchAn86XB7NlSglDTTHZDdO6kyK7jqOeJbaLuORIrh.jpg?versionId=gPo_.gQRYInBSlIFij3FJuxOAdN34AaD" class="list-group-item">Only if they are surrounded with double quote when they are letters.</a>
  C. <a href="http://www.robertomilani.co.uk/wp-content/uploads/2010/12/somethings-missing2-300x226.jpg" class="list-group-item">When it surrounded by single quote, they are letters.</a>
  D. <a href="http://memeguy.com/photos/images/somethings-wrong-7671.png" class="list-group-item">Letters are not able to evaluated in Ruby.</a>
</div>

app/views/coding_adventure/adventure_letter_2.html.erb
<p><h2><kbd> a = "a for Apple" </kbd>,  a is a letter/string?</h2></p>

<div class="list-group">
  A. <a href="http://utahscience.oremjr.alpine.k12.ut.us/sciber99/8th/matter/images/variables.gif" class="list-group-item">Yes, a is letters/strings in this case.</a>
  B. <a href="adventure_letter_3" class="list-group-item">No, a is a variable in this case. But "a for apple" is the letter/string.</a>
  C. <a href="http://www.bulletsnbabesdvd.com/forums/upload/Yi-Long/wrongcattext.jpg" class="list-group-item">No, it need to add single quote around to make it as letters/strings.</a>
  D. <a href="http://www.troll.me/images/pissed-off-obama/hey-guess-what-you-are-wrong.jpg" class="list-group-item">A and C</a>
</div>

app/views/coding_adventure/adventure_letter_3.html.erb
<p><h2><kbd> "dragon" + "girl" </kbd> evaluate to ?</h2></p>

<div class="list-group">
  A. <a href="adventure_letter_4" class="list-group-item">dragongirl</a>
  B. <a href="http://pl.memgenerator.pl/mem-image/so-close-pl-ffffff-9" class="list-group-item">dragon girl</a>
  C. <a href="http://images.sodahead.com/polls/001895649/610621252_You_are_Wrong_520_answer_4_xlarge.jpeg" class="list-group-item">dragon + girl</a>
  D. <a href="http://images.lazygamer.net/2013/01/nope-youre-wrong-look-it-up.jpg" class="list-group-item">A or B</a>
</div>

app/views/coding_adventure/adventure_letter_4.html.erb
<p><h2><kbd> "love" * 4 </kbd> evaluate to ?</h2></p>

<div class="list-group">
  A. <a href="http://quantachange.com/2013/wp-content/uploads/2013/04/oops.jpg" class="list-group-item">love4</a>
  B. <a href="http://images.sodahead.com/polls/002826257/4858235181_no_answer_2_xlarge.jpeg" class="list-group-item">love4444</a>
  C. <a href="adventure_paths" class="list-group-item">lovelovelovelove</a>
  D. <a href="http://fc06.deviantart.net/fs70/f/2013/250/a/7/we_re_so_close__yet_so_far_by_haddasaix-d6lexy9.jpg" class="list-group-item">love love love love</a>
</div>

app/views/coding_adventure/adventure_number_1.html.erb
<p><h2>What does <kbd> 3 + 4 </kbd> evaluate to?</h2></p>

<div class="list-group">
  A. <a href="http://www.jesus-is-savior.com/Hells_Truth/hell_forever_and_ever.jpg" class="list-group-item">12</a>
  B. <a href="http://neurobonkers.com/wp-content/uploads/2011/03/thestupiditburnsmini.jpg" class="list-group-item">-1</a>
  C. <a href="http://static.tvtropes.org/pmwiki/pub/images/garfieldlazy_2816.jpeg" class="list-group-item">3 + 4</a>
  D. <a href="adventure_number_2" class="list-group-item">7</a>
</div>

app/views/coding_adventure/adventure_number_2.html.erb
<p><h2>What does <kbd> 4 * 8 </kbd> evaluate to?</h2></p>

<div class="list-group">
  A. <a href="http://blogs.ancientfaith.com/glory2godforallthings/wp-content/uploads/sites/15/2013/07/Picture-of-Hell.jpg" class="list-group-item">12</a>
  B. <a href="https://s-media-cache-ak0.pinimg.com/736x/d0/dc/ef/d0dceff79109edc9ec48098c7098646f.jpg" class="list-group-item">4 * 8</a>
  C. <a href="http://memeguy.com/photos/images/this-is-how-lazy-i-am-9606.png" class="list-group-item">12</a>
  D. <a href="adventure_number_3" class="list-group-item">32</a>
</div>

app/views/coding_adventure/adventure_number_3.html.erb
<p><h2>What does <kbd> 2**3 </kbd> evaluate to?</h2></p>

<div class="list-group">
  A. <a href="http://tgimpage.com/wp-content/uploads/2012/05/itssoclose.jpg" class="list-group-item">2 to the power 3</a>
  B. <a href="adventure_number_4" class="list-group-item">8</a>
  C. <a href="http://www.quickmeme.com/img/a0/a00d6f748838f7c3755e1cfae97132dfe24ffb49b26d5731a86a0bc7c916a380.jpg" class="list-group-item">2 * 2 * 2</a>
  D. <a href="http://i.ytimg.com/vi/VVIaFqEPVak/hqdefault.jpg" class="list-group-item">2**3</a>
</div>

app/views/coding_adventure/adventure_number_4.html.erb
<p><h2>What does <kbd> 10 / 5 </kbd> evaluate to?</h2></p>

<div class="list-group">
  A. <a href="http://reachingutopia.com/wp-content/uploads/2013/02/drunk-urinal.jpg" class="list-group-item">15</a>
  B. <a href="http://foofygucker.com/Drunk-dog.jpg" class="list-group-item">50</a>
  C. <a href="adventure_number_5" class="list-group-item">2</a>
  D. <a href="http://1.bp.blogspot.com/-hAnnHMF2wm0/UcxKpPly7dI/AAAAAAAAAM0/2ofkKB7Hj_k/s604/foto+anjing+lucu+lagi++narsis+ture+all+size+small+medium+large.jpg" class="list-group-item">2**3</a>
</div>

app/views/coding_adventure/adventure_number_5.html.erb
<p><h2>What does <kbd> 3 / 2 </kbd> evaluate to?</h2></p>

<div class="list-group">
  A. <a href="https://carrotquinn.files.wordpress.com/2013/03/potato27.jpg" class="list-group-item">1.5</a>
  B. <a href="adventure_number_6" class="list-group-item">1</a>
  C. <a href="http://static.lulu.com/browse/product_thumbnail.php?productId=4313995&resolution=320" class="list-group-item">3 / 2</a>
  D. <a href="http://cdn.smosh.com/sites/default/files/ftpuploads/bloguploads/drunk-babies-stein.jpg" class="list-group-item">5</a>
</div>

app/views/coding_adventure/adventure_number_6.html.erb
<p><h2>What code in the following will evaluate to <kbd> 1.5 </kbd> ?</h2></p>

<div class="list-group">
  A. <a href="https://mathwithbaddrawings.files.wordpress.com/2015/02/20150211073701_00006.jpg" class="list-group-item">3.0 / 2.0</a>
  B. <a href="https://i.vimeocdn.com/video/361074133_640.jpg" class="list-group-item">3.0 / 2</a>
  C. <a href="https://chadwickbuchanana.files.wordpress.com/2013/06/8324652.jpg" class="list-group-item">3 / 2.0</a>
  D. <a href="adventure_paths" class="list-group-item">All of above</a>
</div>

app/views/coding_adventure/adventure_paths.html.erb
<h2>I'm going to
  <!-- Split button -->
  <div class="btn-group">
    <button type="button" class="btn btn-danger">Adventure</button>
    <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
      <span class="caret"></span>
      <span class="sr-only">Toggle Dropdown</span>
    </button>
    <ul class="dropdown-menu" role="menu">
      <li><%= link_to 'Numbers Adventure', adventure_number_1_path %></li>
      <li><%= link_to 'Letters Adventure', adventure_letter_1_path %></li>
      <!--<li><%= link_to 'Variables Adventure', adventure_number_1_path %></li>-->
      <!--<li><%= link_to 'Methods Adventure', adventure_number_1_path %></li>-->
      <!--<li><%= link_to 'Git Adventure', adventure_number_1_path %></li>-->
      <li class="divider"></li>
      <li><%= link_to 'Surprise me!', adventure_paths_url %></li>
    </ul>
  </div>
</h2>

app/views/coding_adventure/adventure_start.html.erb
<p><h2>How do I get updated class content if I'm in T4 2038 class?</h2></p>

<div class="list-group">
    A. <a href="adventure_paths" class="list-group-item">cd ~/workspace/davinci_coders_t4_2038/building_the_toolbelt_t4_2038/<br/>git pull</a>
    B. <a href="http://www.pxleyes.com/images/contests/directions/fullsize/Feeling-Lost-4df607dd8f36b_hires.jpg" class="list-group-item">git pull</a>
    C. <a href="https://c2.staticflickr.com/8/7375/8719773915_54a74b3d4b_z.jpg" class="list-group-item">cd ~/workspace/davinci_coders_t4_2038/building_the_toolbelt_t4_2038/</a>
    D. <a href="updated_content" class="list-group-item">git pull T4 2038</a>
</div>

app/views/layouts/_authentication.html.erb
<% if current_user %>
    <li role="presentation" class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false" style="color: white;">
        Logged in as <%= current_user.email %><span class="caret"></span>
      </a>
      <ul class="dropdown-menu" role="menu">
        <li><%= link_to 'View Profile', user_path(current_user.id) %></li><br/>
        <li><%= link_to 'Logout', logout_path, method: :delete %></li>
      </ul>
    </li>
<% else %>
    <li><%= link_to 'Signup', new_user_path, :class => 'navbar-nav', :style => 'color: white;' %></li>
    <li><%= link_to 'Login', login_path, :class => 'navbar-nav', :style => 'color: white;' %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Starter Template for Bootstrap</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </div>
      <ul id="smallmenu" class="navbar navbar-collapse navbar-fixed-top">
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-fixed-top navbar-nav">
          <li><%= link_to 'Study Tools Home', '/', :style => 'color: white;' %></li>
          <li><%= link_to 'Study Exercises', study_exercises_path, :style => 'color: white;' %></li>
          <li><%= link_to 'Users List', users_path, :style => 'color: white;' %></li>
          <li><%= link_to 'Useful Sources', useful_sources_path, :style => 'color: white;' %></li>
          <li><%= link_to 'Coding Adventure', adventure_path, :style => 'color: white;' %></li>
          <li><a href="https://www.davinciinstitute.com/events/" style="color: white;">Events</a></li>
          <!--<li><a href="Mentor Open Schedule">Contact</a></li>-->
          <!--<li><a href="Mentor Info">Contact</a></li>-->
          <ul id="navbar" class="nav navbar-collapse navbar-right">
          <%= render 'layouts/authentication' %>
          </ul>
        </ul>
      </div>
      </ul>
    </div>
  </nav>
  <div class="container content">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", :role => "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/paintings/create.js.erb
<% #if @painting.new_record? %>
//alert("Failed to upload painting: <%= #j @painting.errors.full_messages.join(', ').html_safe %>");
<!--<% #else %>-->
//$("#paintings").append("<%= #j render(@painting) %>");
<% #end %>

app/views/paintings/index.html.erb
<!--<%= #form_for Painting.new do |f| %>-->
  <!--<%= #f.label :image, "Upload paintings:" %>-->
  <!--<%= #f.file_field :image, multiple: true, name: "painting[image]" %>-->
<!--<% #end %>-->

<!--<script id="template-upload" type="text/x-tmpl">-->
<!--<div class="upload">-->
  <!--{%=o.name%}-->
  <!--<div class="progress"><div class="bar" style="width: 0%"></div></div>-->
<!--</div>-->
<!--</script>-->

app/views/study_exercises/ruby_on_rails_exercises.html.erb
<h1> Ruby on Rails Exercises</h1>
<table>
  <tbody>
  <tr>
    <% if current_user %>
      <%= link_to 'How do I get updated class content?', updated_content_path %><br/>
      <%= link_to 'Learn Ruby the Hard Way', lrthw_path %><br/>
      <%= link_to 'Number, Letters and Variables', number_letters_and_variables_path %><br/>
      <%= link_to 'Methods and Flow Control', methods_and_flow_control_path %><br/>
      <%= link_to 'Git 101', git_101_path %><br/>
      <%= link_to 'Git 102', git_102_path %><br/>
    <% else %>
        <td>
          <p id="openpara"><h3>
          Please <%= link_to 'Signup', new_user_path %> to check on study information,
          or <%= link_to 'Login', login_path %> if you are current user.
          </h3></p>
        </td>
    <% end %>
  </tr>
  </tbody>
</table>

app/views/study_exercises/study_exercises.html.erb
<h1 class="study">I am a student of DaVinci, I want to practice</h1><br/>

<h4><%= link_to 'Typing Exercises', 'https://typing.io/' %></h4><br/>
<h4><%= link_to 'Ruby on Rails Exercises', ruby_on_rails_exercises_path %></h4>

app/views/study_exercises/updated_content.html.erb
<h1> Updated Content </h1>

<h2> How do I get updated class content? </h2>
<ul style="list-style: none;">
  <h3> In Terminal, type the following:</h3>
  <pre>
   <h3> >>cd ~/workspace/davinici_coders_*class seccsion*_*class year*/building_the_toolbelt_*class seccsion*_*class year*</h3>
   <h3> >>git pull</h3>
  </pre>
</ul>

app/views/useful_sources/useful_sources.html.erb
<h1>I am a student of DaVinci, I am interesting of</h1><br/>

<h4><%= link_to 'Reading Blogs', reading_blogs_path %></h4><br/>
<h4><%= link_to 'Build my brand', build_my_brand_path %></h4><br/>
<h4><%= link_to 'Pivotal Tracker', pivotal_tracker_path %></h4><br/>

<%= image_tag 'courage.jpg' %>
<%= image_tag 'magic.jpg' %>
<%= image_tag 'try.jpg' %>
<%= image_tag 'Thanks.jpg' %>

app/views/users/_form.html.erb
<%= form_for(@user) do |form| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h4>

      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </p>
  <p>
    <%= form.label :middle_name %>
    <%= form.text_field :middle_name %>
  </p>
  <p>
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </p>
  <p>
  <%= form.label :email %>
  <%= form.text_field :email %>
</p>
  <p>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </p>
  <p>
    <%= form.label :password_confirmation, 'Password Confirmation' %>
    <%= form.password_field :password_confirmation %>
  </p>
  <p>
    <%= form.label :wordpress %>
    <%= form.text_field :wordpress %>
  </p>
  <p>
    <%= form.label :github %>
    <%= form.text_field :github %>
  </p>
  <p>
    <%= form.label :course %>
    <%= form.text_field :course %>
  </p>
  <p>
    <%= form.label :user_type %>
    <%= select_tag :user_type, options_for_select([['Professor', 'Professor'], ['Mentor', 'Mentor'], ['Student', 'Student']]), class: 'genForm_dropBox' %>
  </p>
  <p>
    <%= form.label :bio %>
    <%= form.text_area :bio %>
  </p>
  <p>

    <%= form.submit 'Submit' %>
  </p>
<% end %>

app/views/users/edit.html.erb
<div class="page-header">
  <%= link_to users_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @user, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing user</h1>
</div>

<%= render 'form' %>

app/views/users/new.html.erb
<h2>Signup</h2>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>Profile Page</h1>

<pre><h3>
First Name: <%= @user.first_name %><br/>
Middle Name: <%= @user.middle_name %><br/>
Last Name: <%= @user.last_name %><br/>
Email: <%= @user.email %><br/>
Wordpress: <%= @user.wordpress %><br/>
Github: <%= @user.github %><br/>
Course: <%= @user.course %><br/>
User Type: <%= @user.user_type %><br/>
Bio: <%= @user.bio %><br/>
</h3></pre>

<button type="button" class="btn btn-default"><%= link_to 'Edit', edit_user_path(@user) %></button>
<br/>
<p><h2><%= link_to '>> Start My Coding Adventure <<', adventure_start_path %></h2></p>
<p><h2><%= link_to 'Go to Ruby on Rails Excrcises', ruby_on_rails_exercises_path %></h2></p>